language: ruby
rvm:
  - ree
  - 1.9.2
  - 1.9.3
bundler_args: --without development
gemfile:
  - Gemfile
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_head.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
  exclude:
    - rvm: ree
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_head.gemfile
